inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 1000

Metrics/BlockLength:
  Max: 100

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: False

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - "/spec/factories.rb"
    - "/bin/bundle"